# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
Hello there! :wave: Welcome to the project! :sparkling_heart:
Thank you and congrats :tada: for opening your very first issue in this project. AnitaB.org is an inclusive community, committed to creating a safe and positive environment.
:cherry_blossom: Please follow our [Code of Conduct](https://github.com/anitab-org/mentorship-android/blob/develop/.github/CODE_OF_CONDUCT.md) :raised_hands:
You may submit a PR on the same if you like! If you want to report a bug :beetle: please follow our [bug_report.md](https://github.com/anitab-org/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) template.
Also please make sure you include steps to reproduce it and be patient we will get back to you as soon as we can. :eyes:

Also feel free to join us [AnitaB.org Open Source Zulip Community](https://anitab-org.zulipchat.com/). :handshake: We have different streams for each active repo's for discussions.
:man_technologist: :woman_technologist: Hope you have a great time here :)
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
:tada: Thank you for opening this pull request! :tada:
We really appreciate your time and effort to contribute to this project.
Reminder: Please follow our [Code of Conduct](https://github.com/anitab-org/mentorship-android/blob/develop/.github/CODE_OF_CONDUCT.md) :raised_hands:
For any query ask on [Mentorship Android on Zulip](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/mentorship-android). :handshake:
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
Congrats on merging your first pull request! :tada:
Go ahead and share your your first merge with your colleagues, you got yourself this! :smile: :gift:
