package org.systers.mentorship.remote.services

import org.systers.mentorship.remote.responses.GithubAccessToken
import retrofit2.Call
import retrofit2.http.*

/**
 * This interface describes the methods related to Github SignIn Authentication
 */
interface GithubService {

    /**
     * This function allows a user to login through the Github account
     * @param clientId the Github client id of the application
     * @param clientSecret the Github client secret of the application
     * @param code the temporary code generated by Github to verify user auth.
     * @return a call instance of the [GithubAccessToken]
     */
    @Headers("Accept: application/json")
    @POST("login/oauth/access_token")
    @FormUrlEncoded
    fun loginWithGithub(
            @Field("client_id") clientId: String,
            @Field("client_secret") clientSecret: String,
            @Field("code") code: String
    ): Call<GithubAccessToken>

}
