name: Lint Check

on:
  push:
    branches: [ develop , master ]
  pull_request:
    branches: [ develop , master ]

  workflow_dispatch:
jobs:
  lintcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ./gradlew ktlint
